export const WINDOW_RESIZED = "WINDOW_RESIZED";
export const MOUSE_DOWN = "MOUSE_PRESSED";
export const MOUSE_CLICK = "MOUSE_CLICKED";
export const MOUSE_UP = "MOUSE_RELEASED";
export const MOUSE_MOVE = "MOUSE_MOVED";
export const MOUSE_OVER = "MOUSE_OVER";
export const MOUSE_OUT = "MOUSE_OUT";
export const MOUSE_WHEEL = "MOUSE_WHEEL";
export const SET_MOVIES_CATEGORIES = "MOVIES_CATEGORIES";
export const ADD_MOVIES_CATEGORIES = "MOVIES_CATEGORIES";

export default [
  WINDOW_RESIZED,
  MOUSE_DOWN,
  MOUSE_CLICK,
  MOUSE_UP,
  MOUSE_MOVE,
  MOUSE_OVER,
  MOUSE_OUT,
  MOUSE_WHEEL,
  SET_MOVIES_CATEGORIES,
  ADD_MOVIES_CATEGORIES
];
